services:
  
  app:
    image: ghcr.io/haveagitgat/tdarr:latest
    pull_policy: always
    container_name: tdarr
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      UMASK_SET: 002
      VERSION: docker
      internalNode: "true"
    logging:
      options:
        max-size: 10m
        max-file: 5
    labels:
      traefik.enable: true
      traefik.http.routers.tdarr.entrypoints: https-public
      traefik.http.services.tdarr.loadbalancer.passHostHeader: true
      traefik.http.services.tdarr.loadbalancer.server.url: http://authentik:9000
    networks:
      backend:
    restart: unless-stopped
    volumes:
      - app-config:/app/configs
      - app-data:/app/server
      - app-log:/app/logs
      - /.pool/local:/.pool/local

         
networks:
  backend:
    external: true

volumes:
  app-config:
    driver: local
  app-data:
    driver: local
  app-log:
    driver: local