services:
  app:
    image: ghcr.io/linuxserver/code-server:latest
    container_name: code
    configs:
      - source: app_user_settings
        target: /config/data/User/settings.json
    environment:
      AUTO_UPDATE: true
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:universal-tshoot|linuxserver/mods:code-server-golang|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-extension-arguments
      PUID: 1000
      PGID: 1000
      SUDO_PASSWORD: ${CODE_SUDO_PASSWORD:-super_secret_sudo_password}
      VSCODE_EXTENSION_IDS: catppuccin.catppuccin-vsc|ms-azuretools.vscode-docker|piousdeer.adwaita-theme|Anthropic.claude-code|bierner.markdown-mermaid
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.code.entrypoints: https-public
      traefik.http.services.code.loadbalancer.passHostHeader: true
      traefik.http.services.code.loadbalancer.server.url: http://authentik:9000
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - app-config:/config
      - /mnt:/mnt
      - /.pool:/.pool
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  backend:
    external: true

volumes:
  app-config:
    driver: local

configs:
  app_user_settings:
    content: |  
      {
          "workbench.colorTheme": "Catppuccin Macchiato",
          "workbench.productIconTheme": "adwaita",
          "workbench.iconTheme": null
      }