services:

  app:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: tor
    dns:
      - 1.1.1.1
      - 8.8.4.4
      - 8.8.8.8
    healthcheck:
      test: ["CMD-SHELL","echo", "1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      tor:
    ports:
      - 9150:9150
    restart: unless-stopped
    volumes:
      - app-config:/etc/tor
      - app-data:/var/lib/tor
      - /etc/localtime:/etc/localtime:ro

networks:
  tor:
    external: true

volumes:
  app-config:
    driver: local
  app-data:
    driver: local

    otpauth://totp/andronicsio:andronics@gmail.com?secret=HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ&issuer=andronicsio