services:

  app:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    depends_on:
      - db
      - queue
      - typesense
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - compute
                - gpu
                - video
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.immich.entrypoints: https-public
      traefik.http.services.immich.loadbalancer.passHostHeader: true
      traefik.http.services.immich.loadbalancer.server.port: 2283
    networks:
      - backend
    restart: always
    user: "0:1000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media:/mnt/media
      - /mnt/media/photos:/usr/src/app/upload/library
      - app-upload:/usr/src/app/upload

  db:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    container_name: immich-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_PASSWORD: ${DB_PASSWORD:-"supersecretpassword"}
      POSTGRES_USER: ${DB_USERNAME:-"immich"}
      TZ: Europe/London
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT SUM(checksum_failures) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  ml:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-ml
    depends_on:
      - db
      - queue
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    environment:
      TZ: Europe/London
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ml-cache:/cache

  queue:
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    container_name: immich-queue
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - backend
    restart: always
    volumes:
      - queue-data:/data

  typesense:
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    container_name: immich-typesense
    # env_file:
    #   - .env
    environment:
      GLOB_minloglevel: 1
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:-"super_secret_api_key"}
      TYPESENSE_DATA_DIR: /data
    networks:
      - backend
    restart: always
    volumes:
      - typesense-data:/data


networks:
  backend:
    external: true

volumes:
  app-upload:
    driver: local
  db-data:
    driver: local
  queue-data:
    driver: local
  ml-cache:
    driver: local
  typesense-data:
    driver: local