services:

  app:
    image: ghcr.io/linuxserver/lidarr:latest
    container_name: lidarr
    configs:
      - source: app_config
        target: /config/config.xml
    environment:
      AUTO_UPDATE: true
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.entrypoints: https-public
      traefik.http.services.lidarr.loadbalancer.passHostHeader: true
      traefik.http.services.lidarr.loadbalancer.server.url: http://authentik:9000
    networks:
      - backend
    ports:
      - ${LIDARR_PORT:-8686}:${LIDARR_PORT:-8686}
    restart: unless-stopped
    volumes:
      - app-config:/config
      - /mnt/media:/mnt/media
      - /mnt/transfer:/mnt/transfer
  
  auth:
    image: ghcr.io/goauthentik/proxy
    container_name: lidarr-auth
    environment:
      AUTHENTIK_HOST: ${LIDARR_AUTHENTIK_HOST}
      AUTHENTIK_HOST_BROWSER: ${LIDARR_AUTHENTIK_HOST_BROWSER}
      AUTHENTIK_INSECURE: ${LIDARR_AUTHENTIK_INSECURE}
      AUTHENTIK_TOKEN: ${LIDARR_AUTHENTIK_TOKEN}
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.entrypoints: https-public
      traefik.http.services.lidarr.loadbalancer.passHostHeader: true
    networks:
      backend:
    restart: unless-stopped

  
  metrics:
    image: ghcr.io/onedr0p/exportarr:v1.6.0
    container_name: lidarr-metrics
    command: ["lidarr"]
    environment:
      APIKEY: ${LIDARR_API_KEY:-super_secret_api_key}
      PORT: 9990
      URL: "http://lidarr:${LIDARR_PORT:-8686}"
    networks:
      - backend
    restart: unless-stopped

  
networks:
  backend:
    external: true

volumes:
  app-config:
    driver: local

configs:
  app_config:
    content: |
      <Config>
        <ApiKey>${LIDARR_API_KEY:-super_secret_api_key}</ApiKey>
        <Port>${LIDARR_PORT:-8686}</Port>
        <LogLevel>${LIDARR_LOG_LEVEL:-info}</LogLevel>
        <AuthenticationMethod>Basic</AuthenticationMethod>
        <AuthenticationRequired>Enabled</AuthenticationRequired>
      </Config>