services:
  
  app:
    image: alexta69/metube:latest
    container_name: metube
    environment:
      CUSTOM_DIRS: true
      DOWNLOAD_DIR: /downloads
      STATE_DIR: /config/state
      UID: 1000
      GID: 1000
      UMASK: 022
      YTDL_OPTIONS: "{\"cookiefile\": \"/config/cookies.txt\"}"
    labels:
      traefik.enable: true
      traefik.http.routers.metube.entrypoints: https-public
      traefik.http.services.metube.loadbalancer.passHostHeader: true
      traefik.http.services.metube.loadbalancer.server.url: http://authentik:9000
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - app-config:/config
      - /mnt/transfer/complete/metube:/downloads

networks:
  backend:
    external: true

volumes:
  app-config:
    driver: local